#%RAML 1.0
title: DispatcherService
version: v1
baseUri: https://localhost:8080/DispatcherService/

/pagarFactura:
  description: pagar factura
  post:
    description: pagar factura ingresada.
    body:
      application/json:
        type: |
          {
            "type": "object",
            "$schema": "http://json-schema.org/draft-03/schema",
            "id": "http://jsonschema.net",
            "required": true,
            "contrato": {
                "endPoint": "string",
                "esquema": "string",
                "tipoServicio": "string",
                "idServicio": "string",
                "rutaContrato": "string",
                "wsdlJson": "string",
                "headBody": "string",
                "respExt": "string"
            }
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "resultado": 16
              }
